import '@styles/tailwind.css'
import Head from 'next/head'

function MyApp({ Component, pageProps }) {
  
  return <div >
    <Head>
      <title>My Psicolgy Web</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main >
      <Component {...pageProps} />
      
    </main>
  </div>
}

export default MyApp
